version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/at_secondary"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/at_root/at_root_server"
    schedule:
      interval: "daily"