# The @Protocol root server configuration
root_server:
  # The port to connect to root server
  port: 64
  # The url to connect to root server
  url: 'root.atsign.wtf'

# cicd atsign details
first_atsign_server:
  first_atsign_name: '@cicd1'
  # # The port to connect to first atsign server
  first_atsign_port: 6464
  # # The url to connect to first atsign server
  first_atsign_url: cicd1.atsign.wtf

second_atsign_server:
  second_atsign_name: '@cicd2'
  # # The port to connect to second atsign server
  second_atsign_port: 6464
  # # The url to connect to second atsign server
  second_atsign_url: cicd2.atsign.wtf

notification:
  ### Setting configuration more amenable to the end-to-end tests
  autoNotify: true
  # The maximum number of retries for a notification.
  max_retries: 3
  # The quarantine duration of an atsign. Notifications will be retried max_retries times, every quarantineDuration seconds approximately.
  quarantineDuration: 3
  # The notifications queue will be processed every jobFrequency seconds. However, the notifications queue will always be processed
  # *immediately* when a new notification is queued. When that happens, the queue processing will not run again until jobFrequency
  # seconds have passed since the last queue-processing run completed.
  jobFrequency: 2
  # The time interval(in seconds) to notify latest commitID to monitor connections
  # To disable to the feature, set to -1.
  statsNotificationJobTimeInterval: 15
