name: at_end2end_test
description: End to end tests for at_server
version: 1.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master
  at_lookup: ^3.0.7

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
