name: at_secondary
description: Implementation of secondary server.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  uuid: ^2.0.2
  convert: ^2.1.1
  crypto: ^2.1.4
  crypton: ^1.1.0
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: master
      version: ^1.0.0
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: master
      version: ^1.0.0
  at_lookup: ^1.0.0

dev_dependencies:
  test: ^1.6.0
  test_coverage: ^0.4.1
  mockito: ^4.1.1
  basic_utils: ^2.2.2
