name: at_secondary
description: Implementation of secondary server.
version: 2.0.3
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  convert: ^3.0.0
  crypto: ^3.0.1
  crypton: ^2.0.1
  collection: ^1.15.0
  basic_utils: ^3.0.2
  at_persistence_secondary_server: ^2.0.3
  at_lookup: ^2.0.3
  at_server_spec: ^2.0.3

dependency_overrides:
  at_utils:
    path: ../../../at_tools/at_utils
  at_commons:
    path: ../../../at_tools/at_commons
  at_persistence_secondary_server:
    path: ../at_persistence_secondary_server
  at_server_spec:
    path: ../../at_server_spec

dev_dependencies:
  test: ^1.17.3
  #  test_coverage: ^0.5.0
  mockito: ^5.0.7
