name: at_secondary
description: Implementation of secondary server.
version: 1.1.0-NULLSAFETY
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  convert: ^3.0.0
  crypto: ^3.0.1
  crypton: ^2.0.1
  collection: ^1.15.0
  basic_utils: ^3.0.2
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: null_safety
      version: ^1.1.0

  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: null_safety
      version: ^1.1.0
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: null_safety
      version: ^1.1.0

dev_dependencies:
  test: ^1.17.3
#  test_coverage: ^0.5.0
  mockito: ^5.0.7
