name: at_secondary
description: Implementation of secondary server.
version: 1.0.1+NULLSAFETY
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  convert: ^3.0.0
  crypto: ^3.0.1
  crypton: ^2.0.1
  collection: ^1.15.0
  basic_utils: ^3.0.2
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: null_safety
      version: ^1.0.1+5

  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: null_safety
      version: ^1.0.0+5

  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: null_safety
      version: ^1.0.1

#dependency_overrides:
#  logging: ^1.0.0
#  json_annotation: ^2.3.0

#  at_persistence_secondary_server:
#    path: ../at_persistence_secondary_server
#  at_server_spec:
#    path: ../../at_server_spec
#  at_persistence_spec:
#    path: ../../at_persistence/at_persistence_spec
#  at_utils:
#    path: ../../../at_tools/at_utils
#  at_commons:
#    path: ../../../at_tools/at_commons
#  at_lookup:
#    path: ../../../at_libraries/at_lookup

dev_dependencies:
  test: ^1.17.3
#  test_coverage: ^0.5.0
  mockito: ^5.0.7
