name: at_server_spec
description: A Dart library containing abstract classes that defines what implementations of the root and secondary servers are responsible for.
version: 2.0.5
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/docs/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_commons: ^2.0.4

dev_dependencies:
  pedantic: ^1.11.0
