name: at_server_spec
description: Specification for root and secondary server
version: 1.0.0
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  at_commons:
    git:
      url: git@github.com:atsign-foundation/at_tools.git
      path: at_commons
      ref: master
#dependency_overrides:
#  at_commons:
#    path: ../at_commons
dev_dependencies:
  pedantic: ^1.8.0