name: at_persistence_secondary_server
description: at_persistence_secondary_server is the Persistence layer implementation for @protocol secondary server.
version: 2.0.2
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_secondary_server/index.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  hive: ^2.0.4
  cron: ^0.3.0
  crypto: ^3.0.1
  uuid: ^3.0.4
  at_persistence_spec: ^2.0.0
  at_utils: ^2.0.2
  at_commons: ^2.0.2
  at_utf7: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
