name: at_persistence_secondary_server
description: at_persistence_secondary_server is the Persistence layer implementation for @protocol secondary server.
version: 1.0.1+3
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_secondary_server/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  hive: ^1.3.0
  cron: ^0.2.2
  at_persistence_spec: ^1.0.1+2
  at_utils: ^1.0.1+3
  at_commons : ^1.0.1+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0