name: at_persistence_secondary_server
description: at_persistence_secondary_server is the Persistence layer implementation for @protocol secondary server.
version: 2.0.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_secondary_server/index.html
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  hive: ^2.0.4
  cron: ^0.3.0
  crypto: ^3.0.1
  uuid: ^3.0.4
  at_persistence_spec: ^1.0.1+3
  at_utils: ^1.0.1+8
  at_commons: ^1.0.1+8
  dart_utf7:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: dart_utf7
      ref: trunk
      version: 0.2.1-null-safety

dependency_overrides:
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: trunk
      version: ^1.1.0
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: sdk_refactoring
      version: ^1.1.0
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: sdk_refactoring
      version: ^1.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
