name: at_persistence_secondary_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  hive: ^1.3.0
  cron: ^0.2.2
  at_persistence_spec:
    git:
      url: git://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: master
  at_utils:
    git:
      url: git://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: master
#dependency_overrides:
#  at_persistence_spec:
#    path: ../at_persistence_spec
#  at_utils:
#    path: ../at_utils
#  at_commons:
#    path: ../at_commons
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0