name: at_persistence_spec
description: at_persistence_spec is the Specification for the persistence layer implementation of @protocol development.
version: 1.0.1+3
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_spec/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: dev_env
      version: ^1.0.1+7

dev_dependencies:
  pedantic: ^1.8.0
