name: at_root_server
description: Root server implementation.
version: 1.1.0-NULLSAFETY
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  yaml: ^3.1.0
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: null_safety
      version: ^1.1.0

  at_persistence_root_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_root/at_persistence_root_server
      ref: null_safety
      version: ^1.1.0
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: null_safety
      version: ^1.1.0

dev_dependencies:
  # Adding test_cov for generating the test coverage.
  test_cov: ^1.0.1
  pedantic: ^1.11.0
  test: ^1.17.3
