name: at_root_server
description: Root server implementation.
version: 1.0.0+1
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.0
  redis: ^1.2.0
  uuid: ^2.0.2
  yaml: ^2.2.0
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: dev_env_staging
      version: ^1.0.0

  at_persistence_root_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_root/at_persistence_root_server
      ref: dev_env_staging
      version: ^1.0.0

dev_dependencies:
  # Adding test_cov for generating the test coverage.
  test_cov: ^0.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
