name: at_persistence_root_server
description: Implementation for root server related persistence.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_root_server/index.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redis:
    git:
      url: https://github.com/Derrick56007/redis-dart
      ref: master
      version: ^1.2.1
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: null_safety
      version: ^1.0.1+4

  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: null_safety
      version: ^1.0.1+5

#dependency_overrides:
#  at_persistence_spec:
#    path: ../../../at_server/at_persistence/at_persistence_spec
#  at_utils:
#    path: ../../../at_tools/at_utils

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
  mockito: ^5.0.7
  # commenting test coverage since null safe version is not available
#  test_coverage: ^0.4.1
