name: Auto Assign Bugs to Sprint Planning Project Board

on:
  issues:
    types: [labeled]

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    steps:
      - name: 'Move issue to "Triage"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: atsign-foundation
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Triage"
