name: e2e_test

on:
  workflow_dispatch:

jobs:
  test_running_commands_over_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: list docker services
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker service ls
          host: cicd1.atsign.wtf
          username: ubuntu
          privateKey: ${{ secrets.CICD_SSH_KEY}}
