name: e2e_test on e2e-test branch

on:
  workflow_dispatch:
    branch: e2e-test

jobs:
  test_running_commands_over_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: list services and images on both cicd VMs
        uses: appleboy/ssh-action@master
        with:
          host: "cicd1.atsign.wtf,cicd2.atsign.wtf"
          username: ubuntu
          key: ${{ secrets.CICD_SSH_KEY }}
          script: |
            sudo docker service ls
            sudo docker images

