name: e2e_test on e2e-test branch

on:
  workflow_dispatch:
    branch: e2e-test

jobs:
  test_running_commands_over_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: list docker services on cicd1
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker service ls
          host: cicd1.atsign.wtf
          username: ubuntu
          privateKey: ${{ secrets.CICD_SSH_KEY}}

      - name: list docker services on cicd2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker service ls
          host: cicd2.atsign.wtf
          username: ubuntu
          privateKey: ${{ secrets.CICD_SSH_KEY}}
